spring:
  application:
    name: mq-spring-boot-starter
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

mq:
  type: activemq
  activemq:
    user: admin
    password: admin
    broker-url: tcp://localhost
  tlq:
    naming:
      factory: xx
      provider-url: xx
    queue-factory: xx
    topic-factory: xx
